### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/multi-company#29]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [x] account_type_multi_company - By @luc-demeyer - #73 
- [x] partner_multi_company - By @lasley - #47
- [ ] product_autocompany
- [x] product_multi_company - By @lasley - #35 
- [ ] product_name_unique_per_company
- [ ] sale_layout_multi_company - By @SimoRubi - #83 
- [ ] sales_team_multicompany
- [x] stock_production_lot_multi_company - By @eLBati - #57

**Comment by lasley** [comment]
@pedrobaeza can you please add `partner_multi_company` to this & tag @laslabs to it - referencing  #38. We'll migrate and add the active feature at the same time.

**Comment by pedrobaeza** [comment]
Done

**Comment by angedras** [comment]
Started migration of stock_production_lot_multi_company for 10.0

**Comment by pedrobaeza** [comment]
Maybe you should wait to have this module: https://github.com/OCA/multi-company/pull/39

**Comment by angedras** [comment]
@pedrobaeza ok thanks

**Comment by angedras** [comment]
#39 is  merged, starting the migration of stock_production_lot_multi_company to version 10.0

**Comment by SimoRubi** [comment]
Hi,
I'm working on the migration of [sale_layout_multi_company](https://github.com/OCA/multi-company/tree/8.0/sale_layout_multi_company) in #83
