### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/multi-company#388]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [ ] account_bill_line_distribution - By @Nikul-OSI - #496
- [ ] account_invoice_consolidated - By @MS-OSI - #491
- [x] account_invoice_inter_company - By @chafique-delli - #426
- [ ] account_move_multi_company - By @MS-OSI - #494
- [x] account_multicompany_easy_creation - By @Shide - #425
- [x] base_multi_company - By @atchuthan - #458
- [x] calendar_event_multi_company - By @TelmoSuarez - #680
- [x] calendar_event_type_multi_company - By @TelmoSuarez - #681
- [x] ir_actions_report_multi_company - By @GabbasovDinar - #706
- [x] login_all_company - By @etobella - #777
- [x] mail_multicompany - By @slitheryduke11 - #479
- [x] mail_template_multi_company - By @BT-anieto - #498
- [x] multicompany_configuration - By @etobella - #778
- [x] partner_multi_company - By @SodexisTeam - #460
- [x] pos_restaurant_multi_company - By @legalsylvain - #537
- [x] product_category_company - By @carmenbianca - #470
- [x] product_category_company_favorite - By @legalsylvain - #549
- [x] product_multi_company - By @pilarvargas-tecnativa - #628
- [x] product_tax_multicompany_default - By @Shide - #432
- [x] purchase_sale_inter_company - By @victoralmau - #513
- [x] purchase_sale_stock_inter_company - By @JordiBForgeFlow - #487
- [x] res_company_active - By @legalsylvain - #389
- [x] res_company_category - By @legalsylvain - #392
- [x] res_company_code - By @legalsylvain - #475
- [ ] stock_intercompany - By @yankinmax - #493

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by chafique-delli** [comment]
account_invoice_inter_company: https://github.com/OCA/multi-company/pull/426

**Comment by chafique-delli** [comment]
purchase_sale_inter_company: https://github.com/OCA/multi-company/pull/430

**Comment by chafique-delli** [comment]
purchase_sale_stock_inter_company: https://github.com/OCA/multi-company/pull/446

**Comment by crazyshark2** [comment]
Hi when product_multi_company is upgrade Version 16

**Comment by SodexisTeam** [comment]
WIP - for  product_multi_company, partner_multi_company, base_multi_company

**Comment by amkarthik** [comment]
https://github.com/OCA/multi-company/pull/459 (product_multi_company)
https://github.com/OCA/multi-company/pull/460 (partner_multi_company)

**Comment by slitheryduke11** [comment]
Migrating mail_multicompany: https://github.com/OCA/multi-company/pull/479

**Comment by yankinmax** [comment]
stock_intercompany
- [ ] https://github.com/OCA/multi-company/pull/493

**Comment by BT-anieto** [comment]
I'm working on mail_template_multi_company
https://github.com/OCA/multi-company/pull/498

**Comment by phayasqs** [comment]
Good morning,

Mr @amkarthik  
Do you have any information on when we can expect the full versions of these modules in version 16 of Odoo ?
https://github.com/OCA/multi-company/pull/459 (product_multi_company)
https://github.com/OCA/multi-company/pull/460 (partner_multi_company)

**Comment by antonioburic** [comment]
ir_config_parameter_multi_company 

- [ ] https://github.com/OCA/multi-company/pull/601

**Comment by Kev-Roche** [comment]
hello, I'm migrating : 
- https://github.com/OCA/multi-company/pull/608
- https://github.com/OCA/multi-company/pull/609
- https://github.com/OCA/multi-company/pull/610

**Comment by amh-mw** [comment]
- https://github.com/OCA/multi-company/pull/689
- https://github.com/OCA/multi-company/pull/690
- https://github.com/OCA/multi-company/pull/691
