### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/multi-company#69]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [x] account_invoice_inter_company - By @astirpe - #81
- [ ] account_type_multi_company
- [x] base_multi_company - By @rodrigets - #107 
- [x] partner_multi_company - ~~By @rodrigets - #108~~ - By @cubells - #115 
- [ ] product_autocompany
- [x] product_multi_company - By @cubells - #116
- [ ] product_name_unique_per_company
- [x] product_tax_multicompany_default - By @cubells - #98 
- [x] purchase_sale_inter_company - By @carlosdauden - #97
- [ ] sales_team_multicompany
- [x] stock_production_lot_multi_company - By @misern2 -  #100

**Comment by Yenthe666** [comment]
@pedrobaeza it looks like `account_invoice_inter_company` is migrated but it is not on the app store of Odoo. Perhaps it is nice to add it there too? Only 8.0 is available there.

**Comment by pedrobaeza** [comment]
I will check. I think there's a conflict. I'll tell you.

**Comment by Yenthe666** [comment]
Awesome, thanks a lot.

**Comment by pedrobaeza** [comment]
It's not published because of 

```
account_invoice_inter_company: unmet dependency onchange_helper for series 11.0
```

but that one can't be registered because:
```
Module onchange_helper already exists for another serie. Please use this repository: https://github.com/akretion/ak-odoo-incubator.git.
```

@alexis-via @bealdav can you please check this and tell Apps to remove your one?

@Yenthe666 curiously, this is another issue :wink: :
```
Module auto_backup for series 11.0 belongs to another repository: https://github.com/Yenthe666/auto_backup#11.0
 ```

**Comment by Yenthe666** [comment]
@pedrobaeza thanks for the feedback. About the `auto_backup` repository:  yeah, somebody from OCA once asked me if they could take it into OCA and handle it there. I said yes and also kept/developed for my version. That's why we have the conflict now 😉 
Too bad multiple modules with the same name or not possible from different repositories by the way.

**Comment by pedrobaeza** [comment]
Then maybe you can also donate it in apps for avoiding the problem.

**Comment by Yenthe666** [comment]
I've been wanting to expand & improve it for ages but it is somewhere on the endless "to do" / wishlist hehe.

**Comment by pedrobaeza** [comment]
I mean that say to Apps Manager to remove it yours to allow OCA one to be displayed

**Comment by mamcode** [comment]
Why isn't the module partner_multi_company on this list?

**Comment by pedrobaeza** [comment]
Because it was merged after the branch creation, but I have added it manually.

**Comment by mamcode** [comment]
Good, I am working in that! and also in migration of base_multi_company because it is a dependence... Already I have base_suspend_security (server-tools) done! In the next few days I'll be doing pull requests.

**Comment by pedrobaeza** [comment]
Great, waiting then for your PRs. Please take into account to preserve commit history. You can follow migration guide: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

**Comment by mamcode** [comment]
Thank you @pedrobaeza  I'll take that into account.

**Comment by RoelAdriaans** [comment]
@mamcode Any progress on your migration to 11.0?

**Comment by mamcode** [comment]
@RoelAdriaans Due to changes in the project I was working on I couldn't continue with the migration but I'll take it back this week.

**Comment by RoelAdriaans** [comment]
@mamcode Great! Let me know if you're finished or have any problems.. 
Going to migrate product_multi_company after that

**Comment by mamcode** [comment]
@RoelAdriaans You can count on it!

**Comment by mayjo79** [comment]
Why isn't the module purchase_sale_inter_company on this list?

**Comment by emagdalenaC2i** [comment]
@pedrobaeza Please, add to the list account_invoice_inter_company - By @astirpe - #81 
There is a PR for the migration of product_multi_company - By @cubells - #116 
You could add to the list purchase_sale_inter_company - By @carlosdauden - #97
